name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.PROFILE_GITHUB_TOKEN }}
      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '22.x'
      - name: cache
        uses: actions/cache@v4.2.0
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push README.md
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Vinay Kumar Sharma
          author_email: vinay095.sharma@gmail.com
          default_author: user_info
          message: 'other: Updated README.md file using actions'
          add: '.'
